config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  devise_for :users
  resources :books, exept: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do 
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers"  => "relationships#followers", as: "followers"
  end

  get "searches"  => "searches#search"
  post "searches" => "searches#search"
  #post "searches" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  ## 中間テーブルrelationships(フォローする)とreverse_of_relationships(フォローされる)を作成
  ## Relationshipモデルから外部キーfollower_idを参照にしてrelationshipsという名前の架空のテーブルを作成する
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  ## Relationshipモデルから外部キーfollowed_idを参照にしてreverse_of_relationshipsという名前の架空のテーブルを作成する
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  ## 一覧ページで使う
  ## followingsという名前で架空のテーブルを飛ばしてrelationship.rbファイルのfollowedを参照する
  has_many :followings, through: "relationships", source: :followed

  ## followersという名前で架空のテーブルを飛ばしてrelationship.rbファイルのfollowerを参照する
  has_many :followers,  through: "reverse_of_relationships", source: :follower

  ## フォローする(指定した引数user_idからfollowed_idに対して値を生成する（1人のユーザーが誰かをフォローしたという情報をidで生成する。)
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  ## Relationshipのidを削除する
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  ## フォローしてるかを指定した引数userから判定
  def following?(user)
    followings.include?(user)
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(search, word)
    if search == "perfect"
      User.where(name: word)
    elsif search == "forward"
      User.where("name LIKE ?", word + "%")
    elsif search == "backward"
      User.where("name LIKE ?", "%" + word)
    else
      User.where("name LIKE ?", "%" + word + "%")
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_maching_login_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @book_show = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User Update successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  private
  
  def is_maching_login_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
      <%= link_to user_followers_path(user) do %>
        <%= user.followers.count %>
      <% end %>
      </th>
    </tr>
  </tbody>
</table>

app/views/users/_index.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image %>
          <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', user: @user %>
      <div class="row">
        <%= link_to edit_user_path(@user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <%= render 'index', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td>
              <%= link_to user_followings_path(user.id) do %>
                フォロー数：<%= user.followings.count %>
              <% end %>
            </td>
            <td>
              <%= link_to user_followers_path(user.id) do %>
                フォロワー数：<%= user.followers.count %>
              <% end %>
            </td>
            <td><%= render 'relationships/form', user: user %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', user: @user %>
      <div class="row">
        <% if current_user.following?(@user) %>
          <%= link_to "フォロー外す", user_relationships_path(@user), method: :delete, class: "btn btn-info" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user), method: :post, class: "btn btn-success" %>
        <% end %>
      </div>
      <%= render 'index', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @book_show.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
            <td>
              <%= render 'favorites/favorite', book: book %>
            </td>
            <td>
                コメント数：<%= book.book_comments.count %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>