config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  devise_for :users
  resources :books, exept: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do 
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers"  => "relationships#followers", as: "followers"
  end

  get "searches"  => "searches#search"
  post "searches" => "searches#search"
  #post "searches" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  ## FavoriteテーブルにユーザーIDが存在するか確認する
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect"
      Book.where(title: word)
    elsif search == "foward"
      Book.where("title LIKE ? ", word + "%")
    elsif search == "backward"
      Book.where("title LIKE ? ", "%" + word )
    else
      Book.where("title LIKE ? ", "%" + word + "%")
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_maching_book_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book create successfully"
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book_show = Book.find(params[:id])
    @book = Book.new
    @user = @book_show.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book update successfully"
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  
  def is_maching_book_user
    book = Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
  end
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
      <%= link_to user_followers_path(user) do %>
        <%= user.followers.count %>
      <% end %>
      </th>
    </tr>
  </tbody>
</table>

app/views/books/_index.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errors', obj: @book %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= render 'layouts/errors', obj: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', user: @user %>
      <div class="row">
        <%= link_to edit_user_path(@user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <%= render 'index', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %><br />
                <%= book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
            <td>
              <%= render 'favorites/favorite', book: book %>
            </td>
            <td>
              コメント数：<%= book.book_comments.count %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'form', user: @user %>
      <div class="row">
      <% if current_user.following?(@user) %>
        <%= link_to "フォロー外す", user_relationships_path(@user), method: :delete, class: "btn btn-info" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(@user), method: :post, class: "btn btn-success" %>
      <% end %>
      </div>
      <%= render 'index', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(100,100) %><br />
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @book_show.title, book_path(@book_show) %></td>
            <td><%= @book_show.body %></td>
            <td>
                <%= render 'favorites/favorite', book: @book_show %>
            </td>
            <td>
                コメント数：<%= @book_show.book_comments.count %>
            </td>
            <% if @user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book_show), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book_show), method: :delete, data: { confirm: "削除しますか？"}, class: "btn btn-danger btn-sm" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <h2>Comments</h2>
      <table class="table">
        <tbody>
          <% @book_show.book_comments.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image(100,100) %><br />
              <%= book.user.name %>
            <% end %>
            </td>
            <td>
              <%= book.comment %>
            </td>
            <% if book.user == current_user %>
            <td>
              <%= link_to "Destroy", book_book_comment_path(book), method: :delete, deta: { confirm: "削除しますか？" }, class: "btn btn-danger btn-sm" %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= render 'book_comments/form', book: @book_show, book_comment: @book_comment %>
    </div>
  </div>
</div>