config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  devise_for :users
  resources :books, exept: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do 
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers"  => "relationships#followers", as: "followers"
  end

  get "searches"  => "searches#search"
  post "searches" => "searches#search"
  #post "searches" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_user!
  
  def search
    @range = params[:range]
  
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
      @word = params[:word]
    else
      @books = Book.looks(params[:search], params[:word])
      @word = params[:word]
    end

    render 'searches/searches'
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<div class="container">
  <div class="row text-center d-block">
  <% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: searches_path, local: true, method: :post do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
      <%= f.select :search, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
      <%= f.submit '検索', class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>
  </div>
</div>

app/views/searches/searches.html.erb
<table class="table table-hover table-inverse">
  <% if @range == "User" %>
  <h2>Users search for "<%= @word %>"</h2>
      <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <h2>Books search for "<%= @word %>" </h2>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image(100,100) %></td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>