config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  devise_for :users
  resources :books, exept: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do 
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers"  => "relationships#followers", as: "followers"
  end

  get "searches"  => "searches#search"
  post "searches" => "searches#search"
  #post "searches" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  ## FavoriteテーブルにユーザーIDが存在するか確認する
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect"
      Book.where(title: word)
    elsif search == "foward"
      Book.where("title LIKE ? ", word + "%")
    elsif search == "backward"
      Book.where("title LIKE ? ", "%" + word )
    else
      Book.where("title LIKE ? ", "%" + word + "%")
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  ## 中間テーブルrelationships(フォローする)とreverse_of_relationships(フォローされる)を作成
  ## Relationshipモデルから外部キーfollower_idを参照にしてrelationshipsという名前の架空のテーブルを作成する
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  ## Relationshipモデルから外部キーfollowed_idを参照にしてreverse_of_relationshipsという名前の架空のテーブルを作成する
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  ## 一覧ページで使う
  ## followingsという名前で架空のテーブルを飛ばしてrelationship.rbファイルのfollowedを参照する
  has_many :followings, through: "relationships", source: :followed

  ## followersという名前で架空のテーブルを飛ばしてrelationship.rbファイルのfollowerを参照する
  has_many :followers,  through: "reverse_of_relationships", source: :follower

  ## フォローする(指定した引数user_idからfollowed_idに対して値を生成する（1人のユーザーが誰かをフォローしたという情報をidで生成する。)
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  ## Relationshipのidを削除する
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  ## フォローしてるかを指定した引数userから判定
  def following?(user)
    followings.include?(user)
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(search, word)
    if search == "perfect"
      User.where(name: word)
    elsif search == "forward"
      User.where("name LIKE ?", word + "%")
    elsif search == "backward"
      User.where("name LIKE ?", "%" + word)
    else
      User.where("name LIKE ?", "%" + word + "%")
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_maching_book_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book create successfully"
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book_show = Book.find(params[:id])
    @book = Book.new
    @user = @book_show.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book update successfully"
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  
  def is_maching_book_user
    book = Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
  end
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    ##　本の投稿のIDをURLから取得する。
    book = Book.find(params[:book_id])
    ## ログインしているユーザーのFavoriteテーブルからいいねする投稿のIDのインスタンスを生成する。
    favorite = current_user.favorites.new(book_id: book.id)
    ## いいねする
    favorite.save
    ## 元の画面へ遷移する
    redirect_back fallback_location: root_path
  end

  def destroy
    ## 本の投稿のIDをURLから取得する。
    book = Book.find(params[:book_id])
    ## ログインしているユーザーのFavoriteテーブルからいいねした投稿のIDを取得する。
    favorite = current_user.favorites.find_by(book_id: book.id)
    ## いいねを削除する
    favorite.destroy
    ## 元の画面へ遷移する
    redirect_back fallback_location: root_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_user!
  
  def search
    @range = params[:range]
  
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
      @word = params[:word]
    else
      @books = Book.looks(params[:search], params[:word])
      @word = params[:word]
    end

    render 'searches/searches'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_maching_login_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @book_show = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User Update successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  private
  
  def is_maching_login_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<div class="error_explanation">
  <% if obj.errors.any? %>
    <h3><%= obj.errors.count %> errors</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to root_path, class: "navbar-brand" do %>
        <span>Bookers</span>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collspan navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: "nav-link text-light" do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2ReCreate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
      <p id="notice"><%= flash[:notice] %></p>
      <%= render 'searches/search' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>